# Generated by Django 5.1.3 on 2024-12-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_ingredient_id_reciperequirement_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='MenuItemId',
        ),
        migrations.AddField(
            model_name='purchase',
            name='MenuItems',
            field=models.ManyToManyField(to='inventory.menuitem'),
        ),
    ]
